# gui/ui_text_kr.py
APP_TITLE = "Base Converter (KR)"
LBL_INPUT = "입력"
LBL_FROM = "입력진법"
LBL_TO = "출력진법"
LBL_RESULT = "결과"
LBL_SUMMARY = "요약"
LBL_STEPS = "변환 과정"
BTN_CONVERT = "변환"
BTN_SWAP = "↔"
BTN_CLEAR = "초기화"
BTN_COPY = "복사"
HINT = "좌측에 입력 후 [변환]을 누르세요.\n\n연산 예시: (1011 + A.F) * 2"
ERR_INVALID = "잘못된 입력 또는 계산 불가한 식입니다."
LANG_LABEL = "언어"
